//! Low-level protocol structures and serialisation, autogenerated from `session.capnp`
// (c) 2024 Ross Younger

#![allow(
    missing_debug_implementations,
    single_use_lifetimes,
    unreachable_pub,
    missing_docs,
    clippy::expl_impl_clone_on_copy,
    clippy::match_same_arms,
    clippy::missing_panics_doc,
    clippy::module_name_repetitions,
    clippy::must_use_candidate,
    clippy::needless_lifetimes,
    clippy::semicolon_if_nothing_returned,
    clippy::uninlined_format_args,
    clippy::used_underscore_binding
)]

include!(concat!(env!("OUT_DIR"), "/session_capnp.rs"));
