#!/bin/sh

set -e

if [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_version 2.0
    db_capb
    db_settitle qcp/title
fi

# We cannot meaningfully preconfigure as postinst checks the filesystem at runtime.
