#!/bin/sh -e

# Usage: coverage --stable # stable toolchain only => no doctests
#        coverage # no argument => nightly toolchain only, includes doctests
#        coverage --ci => stable toolchain only, includes doctests, does not generate HTML

# Script prerequisites:
#   Rust toolchain
#   lcov package (for genhtml)
#   cargo install cargo-llvm-cov cargo-nextest

COVERAGE_DIR=target/coverage
NIGHTLY=""
GENHTML=yes

case "$1" in
    "--stable")
        echo "NOTE: Using stable compiler. Excluding doctests."
    ;;
    "--nightly" | "")
        NIGHTLY="+nightly";
        echo "NOTE: Using nightly compiler (including doctests). Run with --stable to use your default set in rustup."
    ;;
    --ci)
        GENHTML=""
        echo "CI mode engaged. Stable compiler, no genhtml run."
    ;;
    *)
        echo "Usage: $0 [--stable|--nightly|--ci]"
        exit 1
    ;;
esac

mkdir -p $COVERAGE_DIR
cargo ${NIGHTLY} llvm-cov clean --workspace
cargo ${NIGHTLY} llvm-cov --all-features --workspace --locked --exclude xtask@0.0.0 --no-report nextest --show-instantiations

if [ -n "${NIGHTLY}" ]; then
    cargo ${NIGHTLY} llvm-cov --all-features --workspace --locked --exclude xtask@0.0.0 --no-report --doc
fi

cargo ${NIGHTLY} llvm-cov --all-features report --doctests --locked --lcov --output-path $COVERAGE_DIR/lcov.info
if [ -n "${GENHTML}" ]; then
    genhtml $COVERAGE_DIR/lcov.info -o $COVERAGE_DIR/html
    echo Coverage written to $COVERAGE_DIR/html
fi
